### ISSUE TITLE
Package review

### ISSUE THREAD

**Issue by lgeistlinger** [ccb-hms/scConform#1]
Hi @tram-nguyen-n it would be very helpful if you could take a look over Daniela's package and see whether you have any comments re: package setup, dependencies, documentation, and demonstration in the vignette.

**Comment by tram-nguyen-n** [comment]
Done! Edits and comments are included in this [pull request](https://github.com/ccb-hms/scConform/pull/4#issue-2354901086) to @DanielaCorbetta
